Update windows.md
defold/doc pull request #433
Opened 2024-05-10 16:47 UTC by mozok

Add example of using ImageMagick suit to convert PNG to ICO.

2024-05-12 21:51 UTC, britzl commented on docs/en/manuals/windows.md
> +3. Prepare your PNG icon.
Where is 2. ?

2024-05-12 21:51 UTC, britzl commented on docs/en/manuals/windows.md
> +1. Instal ImageMagick:
Instal -> Install

2024-05-12 21:53 UTC, britzl commented on docs/en/manuals/windows.md
> +1. Instal ImageMagick:
Also, please move the ImageMagick link from the title to here

2024-05-12 21:53 UTC, britzl requested changes
See comments

2024-05-13 06:55 UTC, mozok commented
Fixed.
*Note to myself: don't do PRs on the Friday evening after release week.

2024-05-13 07:58 UTC, britzl approved these changes
Thanks!

2024-05-13 07:58 UTC, merged