Add documentation about available Docker images for Extender
defold/doc pull request #488
Opened 2024-10-24 14:32 UTC by ekharkunov

Add documentation about available Docker images for Extender and how to use it.

2024-10-30 05:37 UTC, britzl commented on docs/en/manuals/extender-docker-images.md
> +Below is a list of all avaialble Docker images in public Registry. That images can be used to run Extender in environment with old SDK that isn't supported yet.
avaialble -> available

"**The** images can be ... old **SDKs** that **are no longer supported**"

2024-10-30 05:38 UTC, britzl commented on docs/en/manuals/extender-docker-images.md
> +    * **networks** - list of networks that shoud used by Docker container. For running Extender used network with name `default`. Important to set service network aliases (it will be used in later Ex
shoud -> should

2024-10-30 05:39 UTC, britzl requested changes
Some typos but otherwise looks good!

2024-11-02 11:16 UTC, ekharkunov commented
Made fixes according review. Also added RU translation for the document.

2024-11-02 16:58 UTC, AGulev approved these changes

2024-11-04 09:22 UTC, merged